modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL = ""
showAsResourcePack = false

[[mods]]
modId = "embers"
version = "${file.jarVersion}}"
displayName = "Embers"
updateJSONURL = ""
displayURL = "minecraftforge.net"
logoFile = "logo.png"
credits = "Mystic Bois"
authors = "MEAPRITCASCQUUSID"
description = '''
      FLAAAAAAMES
        '''
[[dependencies.embers]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.embers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.embers]]
modId = "lodestone"
mandatory = true
versionRange = "[1.19.2-2.0.0,)"
ordering = "NONE"
side = "BOTH"