modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL = ""
showAsResourcePack = false

[[mods]]
modId = "embers"
version = "${file.jarVersion}"
displayName = "Embers"
#updateJSONURL = ""
#displayURL = "minecraftforge.net"
logoFile = "logo.png"
credits = "Mystic Modding Team"
authors = "Martacus & EpicSquid"
description = '''
Embers is a mod focused around ancient dwarven magi-tech, utilising the fire of the forge to craft wonders.
'''
[[dependencies.embers]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.embers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.embers]]
modId = "lodestone"
mandatory = true
versionRange = "[1.19.2-2.0.0,)"
ordering = "NONE"
side = "BOTH"